booking/models.py
from threading import Lock

class SeatStatus(object):
    """
        Poor man's enum to represent seat statuses
    """
    AVAILABLE, UNAVAILABLE = range(2)


class Seat(object):

    __slots__ = ['row_number', 'seat_number', 'status']

    def __init__(self, row_number, seat_number):
        self.row_number = row_number
        self.seat_number = seat_number
        self.status = SeatStatus.AVAILABLE

    def get_info(self):
        """
            Provides the seat information to be used for
            displaying to the user.

            returns: tuple(string: key, string: info)
        """
        return ("%s_%s" % (self.row_number, self.seat_number),
                "Row: %s Seat: %s" % (self.row_number, self.seat_number))

    def is_available(self):
        """
            Predicate
        """
        return self.status == SeatStatus.AVAILABLE

    def book(self):
        """
            Books the seat by updating the status and
            possibly other fields such as user info, timestamp etc.
        """
        self.status = SeatStatus.UNAVAILABLE
        # add user info.. timestamp etc

    def unbook(self):
        """
            Un-Books the seat by updating the status and
            possibly other fields such as user info, timestamp etc.
        """
        self.status = SeatStatus.AVAILABLE
        # add user info.. timestamp etc

    def __repr__(self):
        return str({'row_number': self.row_number,
                    'seat_number': self.seat_number,
                    'status': self.status})


class Row(object):
    """
        Each Row object has
        -> a list of seats
        -> a list of contiguous seat blocks

           and provides operations for providing
           a way to quickly allocate / release contiguous
           seat blocks.
    """
    def __init__(self, row_number, no_of_seats=10):
        self.row_number = row_number
        self.no_of_seats = no_of_seats
        # reference to seats list
        self.seats = [ Seat(row_number, i) for i in range(no_of_seats)]
        # also maintain a list of contiguous block(s) of seats
        # in the begining there is only one block
        self.contiguous_seats = [self.seats]

    def get_contiguous_seats(self):
        """
            Generator which yields the next block of
            contiguous seats.

            Yields: List of seats
        """
        for block in self.contiguous_seats:
            yield block

    def allocate(self, block_no, no_of_seats):
        """
            This method is called after a successful
            booking of contiguous seats in a block.
            Because we use a logic similar to
            'first fit' we can assume that the seats
            are booked from the start of the block.
            So we basically slice out the free block and
            stick it in the end of the list of free contiguous seats.

        """
        c_seats = self.contiguous_seats
        c_block = c_seats[block_no]
        right = no_of_seats
        rest = c_block[right:]
        # This operation is O(n-m). Its a tradeoff i am taking
        # for fast lookups by using a list
        del c_seats[block_no]
        if rest:
            c_seats.append(rest)
        if not c_seats:
            self.contiguous_seats = [[]]

    def release(self, seats):
        """
            This method is called after a un-successful
            complete booking of split blocks of contiguous seats.
            At this stage the seats have been unbooked.
            Again, because we use a logic similar to
            'first fit' we can assume that the seats
            are booked from the start of the block.
            So we basically merge back the seats into the free block

        """
        c_seats = self.contiguous_seats
        for i, c_block in enumerate(c_seats):
            if c_block:
                first = c_block[0]
                if (seats[-1].seat_number + 1) == first.seat_number:
                    seats.extend(c_block)
                    c_seats[i] = seats
                    return True
        # edge case
        if len(c_seats) == 1:
            if c_seats[0]:
                c_seats.append(seats)
            else:
                empty = c_seats[0]
                empty.extend(seats)
                c_seats[i] = empty
        else:
            c_seats.append(seats)

    def allocate_seat(self, seat):
        """
            This method is called after a successful booking
            of a seat manually by the user. The alogrithm is a bit clever.
            To find the seat quickly i go to each block and check if the
            seat number falls between the first and the last seat in that block.
            Then I get the index by subtracting the first seat number from the
            seat number of the seat provided as input.
            Once i get the index I slice up the left and the right blocks and
            append them to the end.
        """
        c_seats = self.contiguous_seats

        for block_no, c_block in enumerate(c_seats):
            if c_block:
                first, last = c_block[0], c_block[-1]
                if (seat.seat_number >= first.seat_number and
                    seat.seat_number <=last.seat_number):
                    index = seat.seat_number - first.seat_number
                    pre, post = c_block[:index], c_block[index+1:]
                    del c_seats[block_no]
                    if pre:
                        c_seats.append(pre)
                    if post:
                        c_seats.append(post)
                    if not c_seats:
                        self.contiguous_seats = [[]]
                    break


    def __repr__(self):
        return repr(self.__dict__)


class Event(object):
    """
        Each event is represented as
        -> list of row objects each
    """
    def __init__(self, name, event_id, no_of_rows=10, no_seats_per_row=10):
        self.name = name
        self.event_id = event_id
        self.rows = [Row(i, no_seats_per_row) for i in range(no_of_rows)]
        self.lock = Lock()

    def get_contiguous_seats(self):
        """
            Generator function yielding the next contiguous
            block and addtional information for efficient
            'allocation/deallocation'

            Yields: Tuple( Tuple(<row number>, <block number>),
                            List of seats))
        """
        for row in self.rows:
            for i, block in enumerate(row.get_contiguous_seats()):
                if block:
                    yield ((row.row_number, i), block)

    def regroup_contiguous_seats(self, seats, t):
        """
           Given a contiguous list of seats and the
           tuple containing where to find it,
           'allocate the block' and regroup the cached
           contiguous seats list
        """
        row_number, block_no = t
        row = self.rows[row_number]
        row.allocate(block_no, len(seats))

    def release_contiguous_seats(self, seats, t):
        """
           Given a contiguous list of seats and the
           tuple containing where to find it,
           'release the block' into the available seats pool.
        """
        row_number, block_no = t
        row = self.rows[row_number]
        # we cant reliably use block_no from which the seats were sliced out
        row.release(seats)

    def regroup_seat(self, seat):
        """
           When we allocate the seats then we have control over
           where we are placing the seats.

           But if the user requests a specific seat we need to
           'allocate that seat' and fragment the contiguous block
           where this seat this present.
        """
        row = self.rows[seat.row_number]
        row.allocate_seat(seat)

    def get_seat_choices(self):
        """
           Provides the seat information to be displayed to
           the user.

           Returns: List of seat information

        """
        seats = []
        for row in self.rows:
            for seat in row.seats:
                seats.append(seat.get_info())
        return seats

    def get_seats(self, seat_choices):
        """
            After we get back the request from the user
            we parse the info back into the seat objects.

            Returns: List of seats
        """
        seat_tuples = self._parse_seat_info(seat_choices)
        seats = []
        for seat_tuple in seat_tuples:
            row_number, seat_number = seat_tuple
            seat = self.rows[row_number].seats[seat_number]
            seats.append(seat)
        return seats

    def _parse_seat_info(self, seat_choices):
        """
            Helper function to parse the info.

            Returns: List of Tuple(<row number>, <seat number>)
        """
        seat_tuples = []
        for seat_choice in seat_choices:
            row_number, seat_number = map(int, seat_choice.split('_'))
            seat_tuples.append((row_number, seat_number))
        return seat_tuples


class Events(object):
    """
    Note:
        cache events in memory
        ideally you would be getting this from the
        database/in-memory cache..
        this happens when the webserver fires up
    """

    EVENT_NAMES = [('1', 'The_Lion_King'), ('2', 'Bewitched'), ('3', 'Urinetown')]
    EVENT_NAMES_DICT = dict(EVENT_NAMES)
    events = {name: Event(name, i) for i, name in EVENT_NAMES}

    @classmethod
    def get_event(cls, event_id):
        """
           Provides the event object for the given event_id
        """
        event_name = cls.EVENT_NAMES_DICT.get(event_id)
        event = cls.events.get(event_name)
        return event

    @classmethod
    def get_all_events(cls):
        """
           Provides all the events sorted by their event_id
        """
        events = sorted(cls.events.values(), key=lambda x: x.event_id)
        return events

booking/forms.py
from flask_wtf import Form
from wtforms import SelectField, IntegerField, SelectMultipleField
from wtforms import validators


OPTIONS = [('manual', 'Choose by myself'),
           ('autobest', 'Best seats available'),
           ('autobest_with_split', 'Best seats with split'),]



def validate_no_of_seats():
    """
        Custom validator to validate no_of_seats based on
        the OPTIONS provided
    """
    MIN_VALUE = 1
    MIN_VALUE_SPLITS = 4
    MAX_VALUE = 10
    message = 'Must select between %d and %d seats.'

    def _validate_no_of_seats(form, field):
        l = field.data and int(field.data) or 0
        if form['option'].data == 'autobest':
            if l < MIN_VALUE  or l > MAX_VALUE:
                raise validators.ValidationError(message % (MIN_VALUE,
                    MAX_VALUE))
        elif form['option'].data == 'autobest_with_split':
            if l < MIN_VALUE_SPLITS or l > MAX_VALUE:
                raise validators.ValidationError(message % (MIN_VALUE_SPLITS,
                    MAX_VALUE))

    return _validate_no_of_seats

def validate_seats():
    """
        Custom validator to validate seats based on
        the OPTIONS provided
    """
    MIN_SEATS = 1
    MAX_SEATS = 10
    message = 'Must select between %d and %d seats.' % (MIN_SEATS, MAX_SEATS)

    def _validate_seats(form, field):
        l = field.data and len(field.data) or 0
        if form['option'].data == 'manual':
            if l <= 0 or l > MAX_SEATS:
                raise validators.ValidationError(message)

    return _validate_seats


class BookingForm(Form):
    option = SelectField(u'Option', choices=OPTIONS)
    seats = SelectMultipleField(u'Seats',
                    [validate_seats()])
    no_of_seats = IntegerField(u'No of seats',
                    [validate_no_of_seats()], default=0)

booking/views.py
import flask
import time
from datetime import datetime
from .forms import BookingForm
from .models import Events, Event
from .processor import BookingProcessor, BookingError
from pprint import pprint

booking_bp = flask.Blueprint('booking', __name__)



@booking_bp.route('/', methods=['GET'])
def index():
    return flask.render_template('booking_index.html',
        events=Events.get_all_events())


@booking_bp.route('/event/<event_id>', methods=['GET', 'POST'])
def event(event_id):
    form = BookingForm(flask.request.form)
    event = Events.get_event(event_id)
    if not event:
        return flask.redirect('booking.index')
    form.seats.choices = event.get_seat_choices()
    if flask.request.method == 'POST' and form.validate():
        #process
        processor = BookingProcessor(event,
            form.option.data,
            form.seats.data,
            form.no_of_seats.data)
        try:
            processor.process()
        except BookingError, e:
            flask.flash(e.msg, category='danger')
        else:
            flask.flash(u'Booking complete', category='success')
    pprint([x.contiguous_seats for x in event.rows], depth=5)
    return flask.render_template('booking.html', form=form, event=event)

templates/_formhelpers.html
{% macro render_field(field) -%}
    {% set placeholder = '' %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label for="{{ field.id }}" class="control-label">
            {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
        </label>

        {% set class_ = kwargs.pop('class_', '') %}
        {% if field.flags.required %}
            {% set class_ = class_ + ' required' %}
        {% endif %}

        {% if field.type == 'BooleanField' %}
            <div class="checkbox">
                <label>
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            </div>

        {% else %}

            {% if field.type in ('TextField', 'TextAreaField', 'PasswordField', 'FloatField', 'IntegerField') %}
                {% set class_ = class_ + ' input-xlarge form-control' %}

            {% elif field.type == 'DateField' %}
                {% set class_ = class_ + ' input-xlarge form-control datepicker' %}

            {% elif field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file form-control' %}
            {% endif %}

            {% if field.type in ('SelectField', 'SelectMultipleField') %}
                {% set class_ = class_ + ' form-control' %}
                {{ field(class_=class_, **kwargs) }}
            {% else %}

            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
            {% endif %}

        {% endif %}
        {% if field.errors %}
            <span class="help-block">{{ field.errors|join(', ') }}</span>
        {% endif %}
        {% if field.description %}
            <p class="help-block">{{ field.description|safe }}</p>
        {% endif %}
    </div>
{%- endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% block title %}
    <title>Ticketmaestro</title>
    {% endblock title %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Gokulnath Haribabu">

    {% block styles %}
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
              rel="stylesheet">
        <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css"
              rel="stylesheet">
        <style type="text/css">
        /* fill in */
        </style>
    {% endblock styles %}

</head>

<body>

{% from "_formhelpers.html" import render_field%}

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('booking.index')}}">Ticketmaestro</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
{% include 'flash.html' %}
    {% block content %}

    {% endblock content %}
</div>
<!-- /container -->

{% block scripts %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
    <script>
    $('.datepicker').datepicker({
        format: 'yyyy/mm/dd',
    });
    </script>
{% endblock scripts %}
</body>
</html>

templates/booking.html
{% extends "base.html" %}

{% block title %}
    <title>Ticketmaestro</title>
{% endblock title %}

{% block styles %}
  {{ super() }}
<style type="text/css">
  /* fill in */
  .available {
    background-color: green;
    color: white;
    font-weight: bold;
  }
  .unavailable {
    background-color: red;
    color: white;
    font-weight: bold;
  }
</style>
{% endblock styles %}


{% block content %}
<div class="row">
  <p class="lead">{{event.name}}</p>
</div>
<div class="row">
  <div class="col-md-3">
    <p class="lead">Choose...</p>
    <form role="form" method="POST" id='booking_form' role='form'>
        <dl>
            {{ form.hidden_tag() }}
            {{ render_field(form.option) }}
            {{ render_field(form.no_of_seats) }}
            {{ render_field(form.seats) }}
        </dl>
            <p><input type=submit value=Book></p>
    </form>
  </div>
  <div class="col-md-6 col-md-offset-2">
    <p class="lead">Seating Arrangement</p>
    <table class="table table-bordered">
      {% for row in event.rows %}
      <tr>
        <td>
          <b>Row #{{ row.row_number }}</b>
        </td>
        {% for seat in row.seats %}
          <td>
            <div class={{'available' if seat.is_available() else 'unavailable'}}>
              {{ seat.seat_number }}
            </div>
          </td>
        {% endfor %}
      {% endfor %}
      </tr>
    </table>
  </div>
</div>
{% endblock content %}

{% block scripts %}
{{ super() }}
<script>
$(document).ready(function() {
    //do jQuery stuff when DOM is ready
  $( "#option" ).change(function() {
      option = this.value;
      if (option === 'manual') {
        $("#no_of_seats").prop('disabled', true);
        $("#seats").prop('disabled', false);
      }
      // autobest , autobest_with_split
      else {
        $("#no_of_seats").prop('disabled', false);
        $("#seats").prop('disabled', true);
      }
  });
  // trigger it on load
  $( "#option" ).trigger( "change" );
});

</script>
{% endblock scripts %}

templates/booking_index.html
{% extends "base.html" %}

{% block title %}
    <title>Ticketmaestro</title>
{% endblock title %}


{% block content %}
<p class="lead">Choose</p>
{% for event in events %}
  <a href="{{ url_for('booking.event', event_id=event.event_id)}}">{{ event.name }}</a>
  <br>
{% endfor %}
{% endblock content %}

templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endwith %}